theme:
  name: "material"

site_name: GarpixCMS
repo_url: https://github.com/garpixcms/garpixcms

plugins:
- search
- mkdocstrings

nav:
  - Быстрый старт: index.md
  - Установка:
    - Установка зависимостей: install_deps.md
    - Создание нового проекта: install_new_project.md
    - Запускаем проект: install_start_project.md
  - Примеры:
    - Простой корпорат на шаблонах: example_simple_templates_site.md
    - Вход по логину/паролю (SPA): example_auth_spa.md
    - Вход по логину/паролю (шаблоны): example_auth_templates.md
    - Вход через социальные сети:
      - Apple ID: auth/apple.md
    - Уведомления (Email, SMS, PUSH и другие): example_notify.md
  - Пакеты: packages.md
  - Утилиты: utils.md
  - FAQ:
    - CORS: faq_cors.md
    - Создание своего пакета: faq_pack.md
    - Количество выводимых записей в Структуре страниц: faq_list_per_page.md
  - Миграция кода:
    - 1.15.0 -> 2.0.0: migrate/migrate_1.15.0_to_2.0.0.md
  - Устаревшие статьи:
    - Простой корпорат на шаблонах (устарел 10.09.2021): deprecated/example_simple_templates_site_deprecated_2021-09-10.md
