name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag new-image:$(date +%s)

  test:
    runs-on: docker-latest
    services:
      - postgres:11-alpine
    variables:
        SECRET_KEY: runner
        POSTGRES_DB: runner
        POSTGRES_USER: runner
        POSTGRES_PASSWORD: runner
        POSTGRES_HOST: postgres
        POSTGRES_PORT: ''
        TEST: 1

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: echo "SITE_ID=1" >> .env
      run: python3 ./backend/manage.py migrate
      run: python3 ./backend/manage.py qa
